//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkFirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decorator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Decorator()
        {
            this.Firm_Employers = new HashSet<Firm_Employers>();
        }
    
        public int ID_Dec { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Education { get; set; }
        public string Name_Edu_Institution { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firm_Employers> Firm_Employers { get; set; }
    }
}
