//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkFirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm_Employers
    {
        public int Firm_Employers1 { get; set; }
        public Nullable<int> ID_Firm { get; set; }
        public Nullable<int> ID_Decorator { get; set; }
        public Nullable<int> ID_Wardenn { get; set; }
    
        public virtual Decorator Decorator { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual Wardenn Wardenn { get; set; }
    }
}
