//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkFirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant_Area
    {
        public int ID_Plant_Area { get; set; }
        public Nullable<int> ID_Area { get; set; }
        public Nullable<int> ID_Plant { get; set; }
        public Nullable<System.DateTime> Date_Plant { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
