//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkFirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ID_TimeTable { get; set; }
        public Nullable<int> ID_Area { get; set; }
        public Nullable<int> ID_Wardenn { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Wardenn Wardenn { get; set; }
    }
}
