//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkFirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watering_Mode
    {
        public Nullable<int> ID_Watering { get; set; }
        public Nullable<int> ID_Plant { get; set; }
        public int ID_Watering_Mode { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Watering Watering { get; set; }
    }
}
